<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', 'WelcomeController@index');

// ユーザ登録
Route::get('signup', 'Auth\RegisterController@showRegistrationForm')->name('signup.get');
Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');

// ログイン認証
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login')->name('login.post');
Route::get('logout', 'Auth\LoginController@logout')->name('logout.get');

//ユーザーマイページ？ログインユーザのみ
Route::group(['middleware' => ['auth']], function () {
    Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'edit', 'destroy']]);
});

//buyプロフィール
Route::resource('buys', 'BuysController');

//sellプロフィール
Route::resource('sells', 'SellsController');

//rentプロフィール
Route::resource('rents', 'RentsController');




//マイクロポストルーティング
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UsersController', ['only' => ['index', 'show']]);
    Route::resource('microposts', 'MicropostsController', ['only' => ['store', 'destroy']]);
});


//adminログイン関係(ビジネスパーソン）

Auth::routes();

Route::prefix('admin')->name('admin::')->group(function() {
    // For admin auth pages as generated by Auth::routes();
    // See also: https://stackoverflow.com/a/39197278/4821980

    Route::get('/', 'AdminWelcomeController@index')->name('welcome');

    // Authentication Routes...
    Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@login');
    Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

    // // Registration Routes...
    
    Route::get('register', 'Admin\Auth\RegisterController@showRegisterForm')->name('register')->middleware('guest');
    Route::post('register', 'Admin\Auth\RegisterController@register');

    // // Password Reset Routes...
    // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    // Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    Route::get('/show', 'AdminsController@show')->name('admins.show');
    
    Route::get('/create', 'AdminsController@create')->name('admins.create');
    
    Route::post('/store', 'AdminsController@store')->name('admins.store');
    
});

//talksのルーティング　admin
Route::group(['middleware' => 'auth'], function () {
    Route::resource('users', 'UsersController', ['only' => ['index', 'show']]);
    Route::group(['prefix' => 'users/{id}'], function () {
        Route::post('follow', 'TalksController@store')->name('talks.follow');
        Route::delete('unfollow', 'TalksController@destroy')->name('talks.unfollow');
        Route::get('followings', 'TalksController@followings')->name('talks.followings');
        Route::get('followers', 'TalksController@followers')->name('talks.followers');
    });
    

    Route::resource('microposts', 'MicropostsController', ['only' => ['store', 'destroy']]);
});