<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

    Route::get('/', 'WelcomeController@index')->name('welcome');

    // ユーザ登録
    Route::get('signup', 'Auth\RegisterController@showRegistrationForm')->name('signup.get');
    Route::post('signup', 'Auth\RegisterController@register')->name('signup.post');

    // ログイン認証
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login')->name('login.post');
    Route::get('logout', 'Auth\LoginController@logout')->name('logout.get');

    //buyプロフィール
    Route::resource('buys', 'BuysController');

    //sellプロフィール
    Route::resource('sells', 'SellsController');

    //rentプロフィール
    Route::resource('rents', 'RentsController');

    //message　　user一対多message （相談掲示板）未ユーザでも相談フォームを入力できるが新規登録（signup)

    Route::group(['middleware' => ['auth']], function () {
        Route::resource('users', 'UsersController', ['only' => ['index', 'show', 'edit', 'destroy']]);
        Route::resource('messages', 'MessagesController', ['only' => ['index', 'edit', 'destroy', 'store']]);
    });
    
    //message　未ユーザでも相談フォームを入力できるが新規登録（signup)
    Route::get('messages', 'MessagesController@create')->name('message.create');

    //ミドルウェアadmin
    Route::group(['middleware' => ['auth:admin']], function () {
        Route::get('userindex', 'MessagesController@userindex')->name('message.userindex');
        Route::get('/usershow/{id}', 'MessagesController@usershow')->name('message.usershow');
        Route::get('/talks/{id}', 'AdminsController@talks')->name('talks');
        Route::post('admin/talks/store/', 'AdminsController@talksstore')->name('talks.store');
        
    });


   //adminログイン関係(ビジネスパーソン）
    Auth::routes();

    Route::prefix('admin')->name('admin::')->group(function() {
        // For admin auth pages as generated by Auth::routes();
        // See also: https://stackoverflow.com/a/39197278/4821980

        Route::get('/', 'AdminWelcomeController@index')->name('welcome');

        // Authentication Routes...
        Route::get('login', 'Admin\Auth\LoginController@showLoginForm')->name('login');
        Route::post('login', 'Admin\Auth\LoginController@login');
        Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');

        // // Registration Routes...
    
        Route::get('register', 'Admin\Auth\RegisterController@showRegisterForm')->name('register')->middleware('guest');
        Route::post('register', 'Admin\Auth\RegisterController@register');

        // Password Reset Routes...
        // Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
        // Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
        // Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
        // Route::post('password/reset', 'Auth\ResetPasswordController@reset');

        Route::get('/show', 'AdminsController@show')->name('admin.show');
        Route::get('/create', 'AdminsController@create')->name('admins.create');
        Route::post('/store', 'AdminsController@store')->name('admins.store');
        Route::get('/admin', 'AdminsController@admin')->name('admins.admin');
        Route::get('/user/{id}', 'UsersController@user')->name('users.user');
    
    
        Route::group(['middleware' => ['auth']], function () { 
             Route::get('/admins', 'AdminsController@admins')->name('admins.admins');
             Route::get('/index', 'AdminsController@index')->name('admins.index');
             Route::get('/show/{id}', 'AdminsController@showuser')->name('admins.showuser');
        });
    
    });

    //ミドルウェアauth(user)
    Route::group(['middleware' => 'auth'], function () {
        Route::resource('users', 'UsersController', ['only' => ['index', 'show']]);
            Route::group(['prefix' => 'admins/{id}'], function () {
                Route::post('follow', 'FollowingsController@store')->name('followings.follow');
                Route::delete('unfollow', 'FollowingsController@destroy')->name('followings.unfollow');
                Route::get('followings', 'FollowingsController@followings')->name('followings.followings');
                Route::get('followers', 'FollowingsController@followers')->name('follwings.followers');
            });
            
    });

    //talksのルーティング
    Route::group(['middleware' => 'auth:admin'], function () {
        Route::get('talks/{user_id}/{admin_id}', 'TalksController@talkroom');
    
    });   
    

    //Route::resource('microposts', 'MicropostsController', ['only' => ['store', 'destroy']]);
